import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import '@/styles/globals.scss';
import data from '@/data/common.json';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar data={data.header} />
        <main className="main-content">
          <div className="container">{children}</div>
          <Footer data={data.footer} />
        </main>
      </body>
    </html>
  );
}
